# Домашняя работа. Numpy

1. Скачайте этот ноутбук к себе.
2. Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
3. Сохраните результат в своём гитхаб репозитории.

#### Полезная литература

- http://www.numpy.org/
- https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- https://docs.scipy.org/doc/numpy/user/quickstart.html

1) Импортировать numpy и написать версию

In [ ]:
import numpy as np

2) Создать нулевой вектор размера 10

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3) Создать вектор заполненный 7-ами размера 7

In [ ]:
np.full((7),7)

array([7, 7, 7, 7, 7, 7, 7])

4) Создать вектор заполненный четными числами от 10 до 100

In [ ]:
arr = np.arange(102)
print(arr[10:102:2])

[ 10  12  14  16  18  20  22  24  26  28  30  32  34  36  38  40  42  44
  46  48  50  52  54  56  58  60  62  64  66  68  70  72  74  76  78  80
  82  84  86  88  90  92  94  96  98 100]


5) Создать массив случайных чисел и развернуть его задом наперёд

In [ ]:
arr = np.random.randint(0,20, 10)
print(arr[::-1])

[16 12  5 19  3  4  8  3  9  2]


6) Создать двумерную матрицу размера 3 на 3, заполненную числами от 0 до 9

In [ ]:
arr = np.arange(9)
arr = arr.reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


7) Создать матрицу размера 4 на 4 с единицами на диагонали смещеной на один наверх.

In [ ]:
arr = np.eye(4, k=1)
print(arr)

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


8) Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки.

In [ ]:
arr = np.full((4,4) ,7)

print(arr)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


9) Создать матрицу размера 5 на 5 заполненную чилами от 0 до 4 в строках.

In [ ]:
import numpy as np

arr = np.zeros((5,5))
arr += np.arange(5)

print(arr)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


**10**) Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки

In [ ]:
arr = np.random.randint(0, 100, size=(10, 10))
print(arr)
average = np.mean(arr, axis = 1)
center = arr - average[:, np.newaxis]
print(center)

[[14 14 14 10 76 68 74 87 84  7]
 [23 27 28 27 20 36 78 56 65 64]
 [26 96 50 16 71 24 26 45 88 76]
 [19 31 55 23 94 99 57 46 86  7]
 [54 47 66 80 67 42 46 57 61 13]
 [59 19 20 85  2 94 64 74 60 11]
 [16 29 89  6 37 19 31 67 97 51]
 [86 31 98 26 81 99 92 48 22 12]
 [79 19 74 94 33 47 20 41 52 14]
 [48 25 77 47 91 68 47 88 64 58]]
[[-30.8 -30.8 -30.8 -34.8  31.2  23.2  29.2  42.2  39.2 -37.8]
 [-19.4 -15.4 -14.4 -15.4 -22.4  -6.4  35.6  13.6  22.6  21.6]
 [-25.8  44.2  -1.8 -35.8  19.2 -27.8 -25.8  -6.8  36.2  24.2]
 [-32.7 -20.7   3.3 -28.7  42.3  47.3   5.3  -5.7  34.3 -44.7]
 [  0.7  -6.3  12.7  26.7  13.7 -11.3  -7.3   3.7   7.7 -40.3]
 [ 10.2 -29.8 -28.8  36.2 -46.8  45.2  15.2  25.2  11.2 -37.8]
 [-28.2 -15.2  44.8 -38.2  -7.2 -25.2 -13.2  22.8  52.8   6.8]
 [ 26.5 -28.5  38.5 -33.5  21.5  39.5  32.5 -11.5 -37.5 -47.5]
 [ 31.7 -28.3  26.7  46.7 -14.3  -0.3 -27.3  -6.3   4.7 -33.3]
 [-13.3 -36.3  15.7 -14.3  29.7   6.7 -14.3  26.7   2.7  -3.3]]


11) Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца  

In [ ]:
arr = np.random.randint(0, 100, size = (10,10))
print(arr)

median = np.median(arr, axis = 0)
every = arr - median[:, np.newaxis]
print(every)

[[80 23 79 53 45 81 70 37 10 65]
 [ 1 38 26 57 21 64 92 82 32 53]
 [11 99 99 93 45 72 55 70 48 68]
 [74  8 16 88  9 53 12 95  3 96]
 [79 94 17 82  8 97 51 74 40 95]
 [29 24 74 49 42 48 76 72 75 67]
 [63 46 41 73 66 56 97 59 60 78]
 [99 95 26 16 44 75 95 40 46 94]
 [75 46 31 66 33 41 55 16  8 77]
 [48 48 57 96 26 92  6  3 69 22]]
[[ 11.5 -45.5  10.5 -15.5 -23.5  12.5   1.5 -31.5 -58.5  -3.5]
 [-45.   -8.  -20.   11.  -25.   18.   46.   36.  -14.    7. ]
 [-25.   63.   63.   57.    9.   36.   19.   34.   12.   32. ]
 [  4.5 -61.5 -53.5  18.5 -60.5 -16.5 -57.5  25.5 -66.5  26.5]
 [ 41.5  56.5 -20.5  44.5 -29.5  59.5  13.5  36.5   2.5  57.5]
 [-39.  -44.    6.  -19.  -26.  -20.    8.    4.    7.   -1. ]
 [  0.5 -16.5 -21.5  10.5   3.5  -6.5  34.5  -3.5  -2.5  15.5]
 [ 34.5  30.5 -38.5 -48.5 -20.5  10.5  30.5 -24.5 -18.5  29.5]
 [ 32.    3.  -12.   23.  -10.   -2.   12.  -27.  -35.   34. ]
 [-24.5 -24.5 -15.5  23.5 -46.5  19.5 -66.5 -69.5  -3.5 -50.5]]


12) Создать матрицу случайных чисел 5x5. Добавить к ней столбецы максимумов и минимумов по строкам. Получится матрица 5x7.  

In [ ]:
matrix = np.random.randint(0, 100, size = (5, 5))
print(matrix)

max_value = np.max(matrix, axis = 1)
min_value = np.min(matrix, axis = 1)

with_max = np.column_stack((matrix, max_value))
final = np.column_stack((with_max, min_value))
print(final)

[[21 90 48  2 37]
 [47 43 31 70 31]
 [96 42 40 33 93]
 [35 18 77 56 56]
 [ 8 40 76  4 40]]
[[21 90 48  2 37 90  2]
 [47 43 31 70 31 70 31]
 [96 42 40 33 93 96 33]
 [35 18 77 56 56 77 18]
 [ 8 40 76  4 40 76  4]]


13) Вектор чисел от 1 до 51 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрица. Найти произведение этих матриц. Найти обратную матрицу эётого произведения.  

In [ ]:
vector = np.arange(1, 51)

chet = vector[vector % 2 != 0]
nechet = vector[vector % 2 == 0]

chet_matrix = np.array([chet])
nechet_matrix = np.array([nechet])

print(chet_matrix)
print(nechet_matrix)

perem_matrix = chet_matrix * nechet_matrix
print(perem_matrix)

[[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
  49]]
[[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
  50]]
[[   2   12   30   56   90  132  182  240  306  380  462  552  650  756
   870  992 1122 1260 1406 1560 1722 1892 2070 2256 2450]]


14) Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами.

In [ ]:
matrix = np.zeros((8,8))

for i in range(8):
  for j in range(8):
    if (i + j) % 2 == 0:
        matrix[i, j] = 1
    else:
      matrix[i, j] = 0

print(matrix)


[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]
